twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form-theme/bootstrap_4_layout.html.twig'
        - 'form-theme/bootstrap_4_horizontal_layout.html.twig' # to be the default theme

    # @see https://github.com/symfony/symfony/blob/master/UPGRADE-4.4.md#twigbundle
    exception_controller: null
